import { NavBar } from "@/components/Layout";
import { Container } from "@mui/material";

import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Container maxWidth="xl">
          <NavBar />
          {children}
        </Container>
      </body>
    </html>
  );
}
